[package]
authors = ["Reece Stevens <reecestevens24@gmail.com>"]
name = "stm32f40x"
version = "0.1.0"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.2"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.4.0"

[features]
rt = ["cortex-m-rt"]
