[package]
authors = ["ReeceStevens <reecestevens24@gmail.com>"]
name = "f4"
version = "0.1.0"

[dependencies]
cortex-m = "0.4.2"
cortex-m-semihosting = "0.2.0"
bare-metal = "0.1.1"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
version = "0.3.12"

[dependencies.stm32f40x]
features = ["rt"]
optional = false
path = "../stm32f40x"
